### ISSUE TITLE
Unable to generate types for moonbeam network

### ISSUE THREAD

**Issue by bgodlin** [subquery/subql-dictionary#8]
Having a problem indicating the types ts file for moonbeam:
https://github.com/subquery/subql-dictionary/blob/main/moonbeam/src/chaintypes.ts

```
(alias) const typesBundleDeprecated: OverrideBundleType
import typesBundleDeprecated
```

`The inferred type of 'default' cannot be named without a reference to 'moonbeam-types-bundle/node_modules/@polkadot/types/types'. This is likely not portable. A type annotation is necessary.`

**Comment by jiqiang90** [comment]
@bgodlin Hi it seems causing by dependencies conflict issue, https://github.com/subquery/subql-dictionary/commit/72200fc205bcf1b060979fed6d0e784616583ca4. Please try again.

**Comment by bgodlin** [comment]
Thank you!
